name: Continuous Integration
on: push
env:
  DB_NAME: test
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        sudo mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -uroot -proot
    - name: Checkout Repo Code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: Run Linting
      run: |
        go fmt ./...
        go vet ./...
    - name: Run tests
      run: go test
